import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { poppins } from "@/components/ui/fonts";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.className} antialiased px-14 my-5`}>
        <Navbar />

        {children}
      <div className='my-10 text-center'>
        <p className='text-gray-600 text-lg'>
          Copyright &copy;2024 Astroship. All rights reserved
        </p>
      </div>
      </body>
    </html>
  );
}
